apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taskflow

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - serviceaccount.yaml
  - deployment-api.yaml
  - deployment-worker.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
  - poddisruptionbudget.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/instance: taskflow-production
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/techcorp/taskflow-api
    newTag: "1.0.0"
  - name: ghcr.io/techcorp/taskflow-worker
    newTag: "1.0.0"
